In [1]:
import numpy as np

In [3]:
# np.argmax()
# np.argmin()
# np.where()
# np.select()
# np.clip()
# Missing values in arrays
# Typecasting (astype)
# Iteratiing over arrays
# Array Concatenation
# Array Broadcasting

### np.argmax()

In [8]:
# - It returns the index of the maximum number in an array.
# - It treats any n-D array as a 1-D array.
# - In case of multiple maximum, it returns the index of the first occurance of the maximum number.

In [12]:
x=np.array([[10,20,30],[98,50,44],[25,98,77]])
x

array([[10, 20, 30],
       [98, 50, 44],
       [25, 98, 77]])

In [14]:
np.argmax(x)

3

In [16]:
x.ravel()

array([10, 20, 30, 98, 50, 44, 25, 98, 77])

### np.argmin()

In [19]:
# - It returns the index of the minimum number in an array.
# - It treats any n-D array as a 1-D array.
# - In case of multiple minimum, it returns the index of the first occurance of the maximum number.

In [21]:
x=np.array([[10,2,30],[98,50,44],[2,98,77]])
x

array([[10,  2, 30],
       [98, 50, 44],
       [ 2, 98, 77]])

In [23]:
np.min(x)

2

In [25]:
np.argmin(x)

1

In [27]:
x.ravel()

array([10,  2, 30, 98, 50, 44,  2, 98, 77])

In [29]:
x=np.array([[10,20,30],[98,50,44],[2,98,77]])
x

array([[10, 20, 30],
       [98, 50, 44],
       [ 2, 98, 77]])

In [31]:
np.argmin(x)

6

In [33]:
x.ravel()

array([10, 20, 30, 98, 50, 44,  2, 98, 77])

### np.where()

### Case_1

In [37]:
# np.where(condition)

In [39]:
# - It returns a tuple of arrays.
# - The array inside the tuple contains the indexes of elements for which the condition is True.

In [49]:
np.random.seed(446)
x=np.random.randint(10,100,10)

In [51]:
x

array([41, 76, 13, 97, 87, 69, 48, 92, 18, 97])

In [53]:
np.where(x>50)

(array([1, 3, 4, 5, 7, 9], dtype=int64),)

In [55]:
np.where(x<50)

(array([0, 2, 6, 8], dtype=int64),)

In [57]:
np.random.seed(666)
x=np.random.randint(10,100,size=(3,4))

In [59]:
x

array([[12, 55, 40, 72],
       [80, 83, 40, 46],
       [71, 61, 70, 38]])

In [61]:
np.where(x>50)

(array([0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 3, 0, 1, 0, 1, 2], dtype=int64))

In [63]:
np.where(x<50)

(array([0, 0, 1, 1, 2], dtype=int64), array([0, 2, 2, 3, 3], dtype=int64))

In [65]:
x[np.where(x<50)]

array([12, 40, 40, 46, 38])

### Case_2

In [68]:
# np.where(condition, x,y)

In [70]:
# - When the condition gets True then x is the result else y is the result.

In [72]:
x

array([[12, 55, 40, 72],
       [80, 83, 40, 46],
       [71, 61, 70, 38]])

In [76]:
# Even numbers should converted to 1 and the odd numbers should be converted to 0

In [87]:
y=np.where(x%2==0, 1, 0)

In [89]:
y

array([[1, 0, 1, 1],
       [1, 0, 1, 1],
       [0, 0, 1, 1]])

In [91]:
x

array([[12, 55, 40, 72],
       [80, 83, 40, 46],
       [71, 61, 70, 38]])

### Case_3

In [85]:
# np.where(condition, x, arr)

In [97]:
# - When the condition is True then x is the result else no change.

In [93]:
x

array([[12, 55, 40, 72],
       [80, 83, 40, 46],
       [71, 61, 70, 38]])

In [95]:
# all the odd numbers should be 0 rest all the numbers should remain the same.

In [119]:
np.where(x%2!=0, 0, x)

array([[12,  0, 40, 72],
       [80,  0, 40, 46],
       [ 0,  0, 70, 38]])

### Capping

In [132]:
np.random.seed(45)
x=np.random.randint(10,100, size=(3,4))

In [134]:
x

array([[85, 40, 13, 42],
       [71, 95, 45, 78],
       [25, 75, 24, 63]])

In [136]:
# Cap the values in this array in between 30 and 70.
# - Any value that is less than 30 should be 30.
# - Any value that is greater than 70 should be 70.

In [146]:
y=np.where(x<30,30,x)
y

array([[85, 40, 30, 42],
       [71, 95, 45, 78],
       [30, 75, 30, 63]])

In [148]:
res=np.where(y>70,70, y)

In [150]:
res

array([[70, 40, 30, 42],
       [70, 70, 45, 70],
       [30, 70, 30, 63]])

In [152]:
x

array([[85, 40, 13, 42],
       [71, 95, 45, 78],
       [25, 75, 24, 63]])

In [160]:
np.where(x<30,30,
         np.where(x>70,70, x)
        )

array([[70, 40, 30, 42],
       [70, 70, 45, 70],
       [30, 70, 30, 63]])

### np.clip()

In [163]:
# - It caps the values withing lower limit and upper limit.

In [169]:
# np.clip(arr, lower, upper)

In [165]:
x

array([[85, 40, 13, 42],
       [71, 95, 45, 78],
       [25, 75, 24, 63]])

In [167]:
# Cap the values in this array in between 30 and 70.
# - Any value that is less than 30 should be 30.
# - Any value that is greater than 70 should be 70.

In [171]:
np.clip(x, 30, 70)

array([[70, 40, 30, 42],
       [70, 70, 45, 70],
       [30, 70, 30, 63]])

In [183]:
gender=np.array(['male', 'female', 'female', 'not disclosed', 'male', 'unknown', 'male', 'female', 'not defined', 'male'])
gender

array(['male', 'female', 'female', 'not disclosed', 'male', 'unknown',
       'male', 'female', 'not defined', 'male'], dtype='<U13')

In [189]:
# male-1
# female-0
# any other should be -1

In [204]:
np.where(gender=='male',1 , np.where(gender=='female', 0, -1))

array([ 1,  0,  0, -1,  1, -1,  1,  0, -1,  1])

### np.select()

In [206]:
# np.select(condition_list, choice_list, default_value)

In [218]:
st=np.array(['self employed', 'salaried', 'student', 'house wife', 'trader', 'retired', 'pensioner',
         'businessman', 'unemployed', 'jobless', 'freelancer'])

In [220]:
st

array(['self employed', 'salaried', 'student', 'house wife', 'trader',
       'retired', 'pensioner', 'businessman', 'unemployed', 'jobless',
       'freelancer'], dtype='<U13')

In [222]:
# 'self employed' + 'businessman' +'trader' 'freelancer'-> 'businessman'
# 'salaried' + 'pensioner' -> 'salaried'
# 'stident' + 'house wife' + 'unemployed' + 'jobless' + 'retired' -> 'unemployed'

In [226]:
conditions=[st=='self employed', st=='businessman', st=='trader', st=='freelancer',
st=='salaried', st=='pensioner', st=='student', st=='house wife', st=='jobless', st=='retired']

In [232]:
choices=['businessman', 'businessman', 'businessman', 'businessman', 'salaried',
        'salaried', 'unemployed','unemployed', 'unemployed', 'unemployed']

In [234]:
np.select(conditions, choices, default='unemployed')

array(['businessman', 'salaried', 'unemployed', 'unemployed',
       'businessman', 'unemployed', 'salaried', 'businessman',
       'unemployed', 'unemployed', 'businessman'], dtype='<U11')

In [236]:
st

array(['self employed', 'salaried', 'student', 'house wife', 'trader',
       'retired', 'pensioner', 'businessman', 'unemployed', 'jobless',
       'freelancer'], dtype='<U13')

In [238]:
conditions=[st=='self employed', st=='businessman', st=='trader', st=='freelancer',
st=='salaried', st=='pensioner']

In [240]:
choices=['businessman', 'businessman', 'businessman', 'businessman', 'salaried',
        'salaried']

In [242]:
np.select(conditions, choices, default='unemployed')

array(['businessman', 'salaried', 'unemployed', 'unemployed',
       'businessman', 'unemployed', 'salaried', 'businessman',
       'unemployed', 'unemployed', 'businessman'], dtype='<U11')

In [251]:
np.where(st=='trader', 'businessman', 
         np.where(st=='self employed', 'businessman',
                 np.where(st=='freelancer', 'businessman',
                         np.where(st=='businessman', 'businessman',
                                 np.where(st=='salaried', 'salaried',
                                         np.where(st=='pensioner', 'salaried', 'unemployed'))))))

array(['businessman', 'salaried', 'unemployed', 'unemployed',
       'businessman', 'unemployed', 'salaried', 'businessman',
       'unemployed', 'unemployed', 'businessman'], dtype='<U11')

# Conditions on an array

In [254]:
# - We use bitwise and (&), bitwise or (|), and bitwise not (~) rather than logial and, or not with arrays. 

In [258]:
x

array([[85, 40, 13, 42],
       [71, 95, 45, 78],
       [25, 75, 24, 63]])

In [260]:
# Get all the even numbers.

In [262]:
x%2==0

array([[False,  True, False,  True],
       [False, False, False,  True],
       [False, False,  True, False]])

In [264]:
x[x%2==0]

array([40, 42, 78, 24])

In [266]:
x%2!=0

array([[ True, False,  True, False],
       [ True,  True,  True, False],
       [ True,  True, False,  True]])

In [268]:
x[x%2!=0]

array([85, 13, 71, 95, 45, 25, 75, 63])

In [270]:
x

array([[85, 40, 13, 42],
       [71, 95, 45, 78],
       [25, 75, 24, 63]])

In [276]:
# Even numbers that are greater than 50.

(x%2==0)&(x>50)

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [278]:
x[(x%2==0)&(x>50)]

array([78])

In [290]:
x[~x%2==0]

array([85, 13, 71, 95, 45, 25, 75, 63])

# Missing values in arrays

In [293]:
# None is used to represent misisng values in Python.
# np.nan is used to represent the missing values in Numpy.
# np.nan is a float value.

In [297]:
print(type(np.nan))

<class 'float'>


In [303]:
x=np.array([[10,20,np.nan], [40, np.nan,np.nan],[np.nan, 70, 80]])

In [305]:
x

array([[10., 20., nan],
       [40., nan, nan],
       [nan, 70., 80.]])

In [307]:
x.dtype

dtype('float64')

### np.isnan()

In [312]:
# - It checks the missing values and returns a boolean array.

In [316]:
x

array([[10., 20., nan],
       [40., nan, nan],
       [nan, 70., 80.]])

In [314]:
np.isnan(x)

array([[False, False,  True],
       [False,  True,  True],
       [ True, False, False]])

### Get the count of missing values in an array.

In [327]:
np.isnan(x).sum()

4

### Get the count of non-misisng values in an array

In [336]:
np.isnan(x)

array([[False, False,  True],
       [False,  True,  True],
       [ True, False, False]])

In [338]:
~np.isnan(x)

array([[ True,  True, False],
       [ True, False, False],
       [False,  True,  True]])

In [334]:
(~np.isnan(x)).sum()

5

### Get the indexes of missing values

In [345]:
x

array([[10., 20., nan],
       [40., nan, nan],
       [nan, 70., 80.]])

In [350]:
np.isnan(x)

array([[False, False,  True],
       [False,  True,  True],
       [ True, False, False]])

In [343]:
np.where(np.isnan(x))

(array([0, 1, 1, 2], dtype=int64), array([2, 1, 2, 0], dtype=int64))

### Get the indexes of non-missing values

In [354]:
x

array([[10., 20., nan],
       [40., nan, nan],
       [nan, 70., 80.]])

In [352]:
~np.isnan(x)

array([[ True,  True, False],
       [ True, False, False],
       [False,  True,  True]])

In [348]:
np.where(~np.isnan(x))

(array([0, 0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1, 2], dtype=int64))

### Get the missing values

In [359]:
x[np.isnan(x)]

array([nan, nan, nan, nan])

### Get the non-missing values

In [366]:
x[~np.isnan(x)]

array([10., 20., 40., 70., 80.])

### Replacing the missing value

In [369]:
# - Array is mutable.
# - We can modify the elements in an array.

In [371]:
x

array([[10., 20., nan],
       [40., nan, nan],
       [nan, 70., 80.]])

In [377]:
x[np.isnan(x)]=0

In [379]:
x

array([[10., 20.,  0.],
       [40.,  0.,  0.],
       [ 0., 70., 80.]])

### Typecasting

### astype()

In [384]:
# - It is used to typecast an array.

In [386]:
x

array([[10., 20.,  0.],
       [40.,  0.,  0.],
       [ 0., 70., 80.]])

In [388]:
x.dtype

dtype('float64')

In [394]:
y=x.astype(int)

In [396]:
y

array([[10, 20,  0],
       [40,  0,  0],
       [ 0, 70, 80]])

In [398]:
y.dtype

dtype('int32')

In [392]:
x

array([[10., 20.,  0.],
       [40.,  0.,  0.],
       [ 0., 70., 80.]])

In [400]:
x.dtype

dtype('float64')

In [402]:
x

array([[10., 20.,  0.],
       [40.,  0.,  0.],
       [ 0., 70., 80.]])

In [408]:
x[0,0]=np.nan

In [410]:
x

array([[nan, 20.,  0.],
       [40.,  0.,  0.],
       [ 0., 70., 80.]])

In [414]:
# x.astype(int)

In [420]:
x[np.isnan(x)]=0

In [422]:
x

array([[ 0., 20.,  0.],
       [40.,  0.,  0.],
       [ 0., 70., 80.]])

In [424]:
x.astype(int)

array([[ 0, 20,  0],
       [40,  0,  0],
       [ 0, 70, 80]])

# Concatenation of two arrays

In [427]:
# np.concatenate((arr_1, arr_2), axis)

In [431]:
x=x.astype(int)

In [433]:
x

array([[ 0, 20,  0],
       [40,  0,  0],
       [ 0, 70, 80]])

In [435]:
y=np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [437]:
np.concatenate((x,y), axis=0)

array([[ 0, 20,  0],
       [40,  0,  0],
       [ 0, 70, 80],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [439]:
np.concatenate((x,y))

array([[ 0, 20,  0],
       [40,  0,  0],
       [ 0, 70, 80],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [443]:
# np.concatenate((x,y), axis=1)

In [445]:
x

array([[ 0, 20,  0],
       [40,  0,  0],
       [ 0, 70, 80]])

In [447]:
y=np.array([[1],[2],[3]])
y

array([[1],
       [2],
       [3]])

In [449]:
x

array([[ 0, 20,  0],
       [40,  0,  0],
       [ 0, 70, 80]])

In [455]:
np.concatenate((x,y), axis=1)

array([[ 0, 20,  0,  1],
       [40,  0,  0,  2],
       [ 0, 70, 80,  3]])

### Sorting of an array

In [458]:
# np.sort(arr)
# - It sorts an array in ascending order.

In [497]:
np.random.seed(48)
x=np.random.randint(10,100,12)
x

array([10, 61, 91, 78, 58, 74, 80, 80, 44, 90, 39, 16])

In [462]:
np.sort(x)

array([10, 16, 39, 44, 58, 61, 74, 78, 80, 80, 90, 91])

In [464]:
x

array([10, 61, 91, 78, 58, 74, 80, 80, 44, 90, 39, 16])

In [468]:
np.sort(x)[::-1]

array([91, 90, 80, 80, 78, 74, 61, 58, 44, 39, 16, 10])

In [504]:
np.random.seed(48)
x=np.random.randint(10,100,size=(3,4))
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [472]:
np.sort(x)

array([[10, 61, 78, 91],
       [58, 74, 80, 80],
       [16, 39, 44, 90]])

In [474]:
np.sort(x, axis=1)

array([[10, 61, 78, 91],
       [58, 74, 80, 80],
       [16, 39, 44, 90]])

In [476]:
np.sort(x, axis=0)

array([[10, 61, 39, 16],
       [44, 74, 80, 78],
       [58, 90, 91, 80]])

In [478]:
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [488]:
# All the column values in descending order
np.sort(x, axis=0)[::-1]

array([[58, 90, 91, 80],
       [44, 74, 80, 78],
       [10, 61, 39, 16]])

In [490]:
# All the rows values in descending order
np.sort(x)

array([[10, 61, 78, 91],
       [58, 74, 80, 80],
       [16, 39, 44, 90]])

In [494]:
# x

# Iterating over an array

In [500]:
x

array([10, 61, 91, 78, 58, 74, 80, 80, 44, 90, 39, 16])

In [502]:
for i in x:
    print(i)

10
61
91
78
58
74
80
80
44
90
39
16


In [506]:
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [510]:
for i in x:
    print(i)
    print('==============================')

[10 61 91 78]
[58 74 80 80]
[44 90 39 16]


In [512]:
i

array([44, 90, 39, 16])

In [514]:
for j in i:
    print(j)

44
90
39
16


In [522]:
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [520]:
for i in x:
    for j in i:
        print(j)

10
61
91
78
58
74
80
80
44
90
39
16


In [524]:
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [528]:
for i in x.ravel():
    print(i)

10
61
91
78
58
74
80
80
44
90
39
16


In [530]:
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [534]:
x.ravel(order='F')

array([10, 58, 44, 61, 74, 90, 91, 80, 39, 78, 80, 16])

In [536]:
for i in x.ravel(order='F'):
    print(i)

10
58
44
61
74
90
91
80
39
78
80
16


### Transpose of an array

In [540]:
# - Converting the rows into columns and vicer versa is known as transpose of an array.

In [542]:
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [546]:
xt=x.T

In [548]:
xt

array([[10, 58, 44],
       [61, 74, 90],
       [91, 80, 39],
       [78, 80, 16]])

In [550]:
x

array([[10, 61, 91, 78],
       [58, 74, 80, 80],
       [44, 90, 39, 16]])

In [558]:
for i in x.T:
    for j in i:
        print(j)

10
58
44
61
74
90
91
80
39
78
80
16


# Array Broadcasting

In [563]:
# - When we perform some operation on two arrays of different shapes.
# - The Numpy matches the shape of the arrays by adding dummy rows or dummy columns to make the operation possible.
# - This concept is known as array broadcasting.

In [565]:
# - At least one dimension should match in both the arrays.
# - The other dimension should be 1 in either of the arrays.

In [569]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [571]:
y=np.array([[2,4,6]])
y

array([[2, 4, 6]])

In [573]:
x.shape

(3, 3)

In [575]:
y.shape

(1, 3)

In [587]:
x+y

array([[ 3,  6,  9],
       [ 6,  9, 12],
       [ 9, 12, 15]])

In [589]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [593]:
y=np.array([[2],[2],[4]])

In [595]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [597]:
y

array([[2],
       [2],
       [4]])

In [599]:
x.shape

(3, 3)

In [601]:
y.shape

(3, 1)

In [603]:
x+y

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [11, 12, 13]])

In [605]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [609]:
y=np.array([[1,2,3],[4,5,6]])

In [611]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [613]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [615]:
x.shape

(3, 3)

In [617]:
y.shape

(2, 3)

In [619]:
x+y

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [621]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [623]:
x*5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [629]:
y=np.full_like(x, 5)

In [631]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [633]:
y

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [635]:
x*y

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])