In [1]:
import re

In [5]:
textt= 'Snehal&&**#Raghu_)(*&& Maya Shashi!@# Manoj 89&&&&Sandeep 89$%#Gandhar Baby'

pat=r'[^A-Za-z]+'

re.split(pat,textt)   #- Why is _ getting displayed in the output here


['Snehal', 'Raghu', 'Maya', 'Shashi', 'Manoj', 'Sandeep', 'Gandhar', 'Baby']

In [9]:
# for i in range(ord('A'), ord('z')+1):
#     print(chr(i))

# Numpy

In [21]:
# - Numpy stands for Numerical Python.
# - It is a Python library that is used to perform advanced numerical computations on large data.
# - Using Numpy we can perform statistical, Arithmetic, Linear Algebric, Trignometric etc. operations on large data.
# - Using Numpy we can simulate random numbers.
# - Numpy provides a very important and useful dta structure known as array

### Importing Numpy

In [27]:
import numpy as np

### Version

In [30]:
np.__version__

'1.26.4'

In [34]:
# !pip install --upgrade numpy

# Array

In [37]:
# - An array is a collection of homogenous (same type) elements.
# - Using arrays we can perform complex operations with less code.
# - Arrays are faster than loops.

In [49]:
lst=[i for i in range(1,11)]
print(lst)

# Multiply each number with 5
res=[]
for i in lst:
    res.append(i*5)
print(res)

print(list(map(lambda x:x*5, lst)))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [55]:
arr=np.arange(1,11)
# Multiply each number with 5
arr*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [59]:
import time

In [65]:
time.time()

1754319746.6603503

In [67]:
start_time=time.time()
lst=[i for i in range(1,1000000)]
res=[]
for i in lst:
    res.append(i*5)

print(res[0], res[-1])
end_time=time.time()

time_taken=end_time-start_time
print(time_taken)

5 4999995
0.16010522842407227


In [75]:
start_time=time.time()
arr=np.arange(1,1000000)
# Multiply each number with 5
arr*5

end_time=time.time()
time_taken=end_time-start_time
print(time_taken)

0.002663135528564453


In [81]:
# print(1.1*1000)
# print(1.001*1000)

# Creating an array

In [85]:
# np.array(list/tuple)

In [91]:
lst=[10,20,30,40,50]
x=np.array(lst)
print(x, type(x))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [93]:
x

array([10, 20, 30, 40, 50])

In [100]:
lst= (10,20,30,40,50)
x=np.array(lst)
# print(x, type(x))
x

array([10, 20, 30, 40, 50])

# Attributes on Arrays

In [98]:
# - size
# - shape
# - dtype
# - ndim

### size

In [103]:
# - It returns the number of elements an array contains.

In [105]:
x

array([10, 20, 30, 40, 50])

In [107]:
x.size

5

In [113]:
len(x)

5

### shape

In [116]:
# - It returns a tuple of one or more elements.
# - If only one element is there in the tuple the it represents the number of elements in an array.
# - If there are two elements in the tuple thne they represent rows and columns.

In [118]:
x

array([10, 20, 30, 40, 50])

In [124]:
x.shape

(5,)

In [130]:
y=np.array([[10,20,30],[40,50,60]])
y

array([[10, 20, 30],
       [40, 50, 60]])

In [132]:
y.shape

(2, 3)

In [134]:
len(x)

5

In [136]:
len(y)

2

In [140]:
y.size

6

### dtype

In [143]:
# - It returns the data type of the elements that the contains.

In [145]:
x

array([10, 20, 30, 40, 50])

In [147]:
x.dtype

dtype('int32')

In [149]:
x=np.array([1.5,2.6,3.4,8.2,5.5])

In [151]:
x

array([1.5, 2.6, 3.4, 8.2, 5.5])

In [153]:
x.dtype

dtype('float64')

### ndim

In [156]:
# - It returns the dimension of an array.

In [174]:
x=np.array(55)
x

array(55)

In [176]:
x.ndim

0

In [178]:
x.shape

()

In [180]:
x=np.array([55, 44, 33,22, 88])
x

array([55, 44, 33, 22, 88])

In [182]:
x.ndim

1

In [184]:
x.shape

(5,)

In [186]:
y=np.array([[10,20,30],[40,50,60]])
y

array([[10, 20, 30],
       [40, 50, 60]])

In [190]:
y.shape

(2, 3)

In [188]:
y.ndim

2

# Array Upcasting

In [197]:
# - When we pass heterogenous elements to an array then it performs upcasting.
# - It converts the type of teh elements into one type as per for the following hierarchy.

# int -> float -> complex -> str -> object.

In [201]:
x=np.array([1,2,3,4,5,6,7,8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [203]:
x.dtype

dtype('int32')

In [205]:
x=np.array([1,2,3,4,5.2,6,7,8])
x

array([1. , 2. , 3. , 4. , 5.2, 6. , 7. , 8. ])

In [207]:
x.dtype

dtype('float64')

In [213]:
x=np.array([1,2,3.2,4+6j,5,6,7,8])
x

array([1. +0.j, 2. +0.j, 3.2+0.j, 4. +6.j, 5. +0.j, 6. +0.j, 7. +0.j,
       8. +0.j])

In [215]:
x.dtype

dtype('complex128')

In [217]:
x=np.array([1,2,3.2,4+6j,'5',6,7,8])
x

array(['1', '2', '3.2', '(4+6j)', '5', '6', '7', '8'], dtype='<U64')

In [221]:
x=np.array([1,'2',3.2,4+6j,[5,6],7,8], dtype =object)
x

array([1, '2', 3.2, (4+6j), list([5, 6]), 7, 8], dtype=object)

In [223]:
x=np.array([1,'2',3.2,4+6j,(5,6),7,8], dtype =object)
x

array([1, '2', 3.2, (4+6j), (5, 6), 7, 8], dtype=object)

# Creating different kind of arrays

### np.arange()

In [227]:
# - It is similar to range() in Python.
# - It returns a 1-D array of numbers within a range.

In [245]:
# np.arange(start, stop, step)
# stop is excluded
# step is 1 by default.

# We can specify a float step in arange()

In [235]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [239]:
x=np.arange(2,21,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [243]:
# 10 to 1

x=np.arange(10,0,-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [251]:
# list(range(1,10,.5))

In [255]:
x=np.arange(1,10,.5)
x

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

### linspace()

In [258]:
# - It returns a 1-D array of equally spaced values.

In [260]:
# np.linspace(start, stop, number_of_elements)

# start and stop both are included.

In [262]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [266]:
# Arithmetic Progression

# l=a+(n-1)d
# l= last_term
# a= first term
# n= total numbers
# d= common difference

In [270]:
# 10=1+(5-1)d
# 10-1=(4)d
d=9/4
d

2.25

In [280]:
np.linspace(1,5,100000)

array([1.     , 1.00004, 1.00008, ..., 4.99992, 4.99996, 5.     ])

### np.zeros()

In [283]:
# - It creates an array of zeros of the given shape.

In [285]:
# np.zeros((rows, cols))

In [291]:
# Create a 3*4 array of zeros

x=np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [293]:
x.dtype

dtype('float64')

In [295]:
x=np.zeros((3,4), dtype=int)
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [300]:
x.dtype

dtype('int32')

### np.ones()

In [303]:
# - It returns an array of 1's of the given shape

In [305]:
# np.ones((rows, cols))

In [309]:
x=np.ones((3,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [311]:
x.dtype

dtype('float64')

In [313]:
x=np.ones((3,4), dtype=int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### np.eye()

In [316]:
# - It returns an identity matrix.

In [318]:
# np.eye(rows,cols)

In [322]:
# Craete a 3*3 identity matrix

x=np.eye(3,3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [324]:
x.dtype

dtype('float64')

In [326]:
x=np.eye(3,3, dtype=int)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [328]:
x=np.eye(3,4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### np.full()

In [331]:
# - It returns an array of the given shape and the given value.

In [333]:
# np.full((rows, cols), value)

In [335]:
# Create a 3*4 array where all the values are 2.5

In [345]:
x=np.full((3,4),2.5)
x

array([[2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5]])

In [349]:
np.zeros((3,4))+2.5

array([[2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5]])

In [353]:
np.ones((3,4))*2.5

array([[2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5]])

### np.zeros_like()

In [356]:
# - It takes an array as argument.
# - It returns an array of 0's of the shape of the given array.

In [358]:
# np.zeros_like(arr)

In [364]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[5,6,7],[5,6,4]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 6, 7],
       [5, 6, 4]])

In [366]:
arr.shape

(5, 3)

In [368]:
np.zeros_like(arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [370]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 6, 7],
       [5, 6, 4]])

In [372]:
arr*0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [374]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 6, 7],
       [5, 6, 4]])

### np.ones_like()

In [377]:
# - It takes an array as argument.
# - It returns an array of 1's of the shape of the given array.

In [379]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 6, 7],
       [5, 6, 4]])

In [381]:
np.ones_like(arr)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### np.full_like()

In [384]:
# - It takes an array and a value as arguments.
# - It returns an array of the shape of the given array filled with the given value.

In [386]:
# np.full_like(arr)

In [388]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [5, 6, 7],
       [5, 6, 4]])

In [390]:
np.full_like(arr, 55)

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [394]:
np.full_like(arr, 2.5, dtype=float)

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [408]:
np.full_like(arr, 'a', dtype=str)

array([['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a']], dtype='<U1')

In [398]:
int('a')

ValueError: invalid literal for int() with base 10: 'a'

# Creating 2-D array

### By using a 2-D list

In [413]:
lst=[[10,20,30],[40,50,60]]
lst

[[10, 20, 30], [40, 50, 60]]

In [417]:
x=np.array(lst)
x

array([[10, 20, 30],
       [40, 50, 60]])

In [419]:
x.shape

(2, 3)

In [421]:
x.ndim

2

In [423]:
x.size

6

In [425]:
len(x)

2

In [447]:
lst=[[10,20,30],[40,50,60,80]]
lst

[[10, 20, 30], [40, 50, 60, 80]]

In [451]:
np.array(lst, dtype=object)

array([list([10, 20, 30]), list([40, 50, 60, 80])], dtype=object)

### By using reshape() or shape

### reshape()

In [430]:
# - It returns a new array after reshaping

In [455]:
x=np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [453]:
# arr.reshape(rows, cols)

In [457]:
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [459]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [461]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [463]:
x.reshape(3,5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [467]:
# Create a 3*5 array of numbers from 1 to 15

x=np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [471]:
y=x.reshape(3,5)

In [473]:
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [475]:
x=np.arange(1,16).reshape(3,5)

In [477]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### shape

In [480]:
# - It is a tuple.
# - It makes the changes in the existing array.

In [482]:
# arr.shape=(rows, cols)

In [488]:
x=np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [490]:
x.shape=(3,5)

In [492]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [494]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [496]:
x.shape=(5,3)

In [498]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# Creating a 3-D array

In [501]:
# - When we repeat a 2-D array then we get a 3-D array.

### By using a 3-D list

In [508]:
lst=[[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]]
lst

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

In [512]:
x=np.array(lst)
x

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [514]:
x.shape

(3, 2, 3)

In [516]:
x.ndim

3

### By using reshape() or shape

In [521]:
# Create a 3*2*4 array

x=np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [527]:
y=x.reshape(3,2,4)
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [529]:
y.shape

(3, 2, 4)

In [531]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [533]:
x.shape=(3,2,4)

In [535]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])